environment:
  GH_TOKEN:
    secure: IOg+qGyyMMk72bZMBUn60Nbshg0k7doVDKQzb1bsGsvyd6R3R7XIRmTJH/CAN4mm
install:
  - ps: |
      npm i npm@latest -g
      Install-Product node 9
      $ENV:CI=true
      $ENV:PATH=$ENV:APPDATA + "\npm;" + $ENV:PATH
      npm i --no-optional
skip_tags: true
shallow_clone: true
test_script:
  - ps: |
      node --version
      npm -v
      npm test
platform: x64
build: off
matrix:
  fast_finish: true
