sudo: required
os: 
  - osx
  - linux
language: node_js
node_js:
  - "9"
addons:
  chrome: stable
  apt:
    packages:
    - python2.7
    - python2.7-dev
before_install:
  - echo "$TRAVIS_OS_NAME"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew outdated rpm || brew install rpm;
      brew outdated python2 || brew install python2;
    fi;
install:
  - yarn install
after_success: 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      yarn coverage;
      if [[ $TRAVIS_BRANCH == "development" ]] || [[ $TRAVIS_BRANCH == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" = "false"]]; then
          yarn dist:publish-unix;
      fi;
    fi;
